apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: lucasorramon/hello-go-2:v7.3
          startupProbe: # Inicializou?
            httpGet:
              path: /healthz
              port: 9090
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe: # Pronto para receber tráfego?
            httpGet:
              path: /healthz
              port: 9090
            periodSeconds: 3
            failureThreshold: 1
#            initialDelaySeconds: 10

          livenessProbe: # Vivo?
            httpGet:
              path: /healthz
              port: 9090
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
#            initialDelaySeconds: 15
          
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
      
          volumeMounts:
            - name: config
              mountPath: /go/myfamily
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt
